# Generated by Django 2.2.7 on 2020-04-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=40)),
                ('edition', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['isbn'],
            },
        ),
    ]
