# Generated by Django 2.2.7 on 2020-04-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200413_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(blank=True, choices=[('literature', ((11, 'fiction'), (12, 'novel'))), ('academic', ((21, 'History'), (22, 'novel')))], default='11', max_length=1),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
