# Generated by Django 2.2.7 on 2020-04-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200414_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(blank=True, choices=[('Literature', ((11, 'Fiction'), (12, 'Novel'), (13, 'Poetry'))), ('Academic', ((21, 'CSE'), (22, 'EEE'), (23, 'BBA')))], help_text='Select a book genre', max_length=1),
        ),
    ]
