# Generated by Django 2.2.7 on 2020-04-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200414_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_died',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(default='Bangle', help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default='available', max_length=32),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(blank=True, choices=[('Literature', ((11, 'Fiction'), (12, 'Novel'), (13, 'Poetry'), (14, 'Rendering'), (15, 'Essays'), (16, 'Short Story'), (17, 'Drama'))), ('Academic', ((21, 'Computer Science and Engineering'), (22, 'Electrical & Electronics Engineering'), (23, 'Bachelor of Business Administration'), (24, 'Law and Justice'), (25, 'PHARMACY'), (26, 'Anthropology'), (27, 'History'), (28, 'Philosophy'), (29, 'Economics'), (30, 'Political Science'), (31, 'Psychology'), (32, 'Sociology'), (33, 'Physics'), (34, 'Bio-Chemistry'), (35, 'Zoology')))], help_text='Select a book genre', max_length=1),
        ),
        migrations.AlterModelTable(
            name='books',
            table='book',
        ),
    ]
