# Generated by Django 2.2.7 on 2020-04-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200414_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='summary',
            field=models.TextField(default='write summary of book', help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
