# Generated by Django 2.2.7 on 2020-04-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(blank=True, choices=[('Literature', (('11', 'Fiction'), ('12', 'Novel'), ('13', 'Poetry'), ('14', 'Rendering'), ('15', 'Essays'), ('16', 'Short Story'), ('17', 'Drama'))), ('Academic', (('21', 'Computer Science and Engineering'), ('22', 'Electrical & Electronics Engineering'), ('23', 'Bachelor of Business Administration'), ('24', 'Law and Justice'), ('25', 'PHARMACY'), ('26', 'Anthropology'), ('27', 'History'), ('28', 'Philosophy'), ('29', 'Economics'), ('30', 'Political Science'), ('31', 'Psychology'), ('32', 'Sociology'), ('33', 'Physics'), ('34', 'Bio-Chemistry'), ('35', 'Zoology')))], help_text='Select a book genre', max_length=1),
        ),
    ]
