# Generated by Django 2.2.7 on 2020-07-16 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_died', models.DateField(blank=True, null=True, verbose_name='died')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn ">ISBN number</a>', max_length=13, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('book_name', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=30)),
                ('summary', models.TextField(default='write summary of book', help_text='Enter a brief description of the book', max_length=1000)),
                ('genre', models.CharField(blank=True, choices=[('Literature', (('11', 'Fiction'), ('12', 'Novel'), ('13', 'Poetry'), ('14', 'Rendering'), ('15', 'Essays'), ('16', 'Short Story'), ('17', 'Drama'))), ('Academic', (('21', 'Computer Science and Engineering'), ('22', 'Electrical & Electronics Engineering'), ('23', 'Bachelor of Business Administration'), ('24', 'Law and Justice'), ('25', 'PHARMACY'), ('26', 'Anthropology'), ('27', 'History'), ('28', 'Philosophy'), ('29', 'Economics'), ('30', 'Political Science'), ('31', 'Psychology'), ('32', 'Sociology'), ('33', 'Physics'), ('34', 'Bio-Chemistry'), ('35', 'Zoology')))], default='12', help_text='Select a book genre', max_length=20)),
                ('language', models.CharField(choices=[('BANGLE', 'bangle'), ('ENGLISH', 'english'), ('FRENCH', 'french'), ('JAPANESES', 'japaneses'), ('HINDI', 'hindi')], default='BANGLE', help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default='AVAILABLE', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book.Author')),
            ],
            options={
                'db_table': 'Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyOfBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_of_book_code', models.CharField(max_length=250, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_of_book', to='book.Book')),
            ],
            options={
                'db_table': 'Copy_of_books',
            },
        ),
    ]
