# Generated by Django 2.2.7 on 2020-07-19 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_auto_20200716_0509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Date Of Issue')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Date Of Return')),
                ('borrow_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow', to='book.CopyOfBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
