# Generated by Django 2.2.7 on 2020-07-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name': 'Borrow', 'verbose_name_plural': 'Borrows'},
        ),
        migrations.AlterModelTable(
            name='borrow',
            table='borrows',
        ),
    ]
